# Generated by Django 5.2.8 on 2025-11-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('flag', models.ImageField(upload_to='flags/')),
            ],
        ),
        migrations.RemoveField(
            model_name='plant',
            name='native_to',
        ),
        migrations.AddField(
            model_name='plant',
            name='native_countries',
            field=models.ManyToManyField(related_name='plants', to='plants.country'),
        ),
    ]
